import Head from "next/head";
import Location from "../components/pages/Location.js";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Damage Intelligence</title>
        <meta name="description" content="Generated by Remote Roofing" />
      </Head>
      <Location />
    </div>
  );
}
